import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';
export const users = sqliteTable('users', {
    id: text('id').primaryKey(), // Discord User ID
    username: text('username'),
    avatar: text('avatar'),
    accessToken: text('accessToken'),
    refreshToken: text('refreshToken'),
    guilds: text('guilds', { mode: 'json' }), // JSON string for Discord Guilds
    subscriptionStatus: text('subscriptionStatus'), // 'active', 'inactive', 'tester', 'owner' etc
    expiresAt: text('expiresAt'),
});
export const servers = sqliteTable('servers', {
    id: text('id').primaryKey(), // Discord Server ID
    channels: text('channels', { mode: 'json' }), // Cached channels
    channelsFetchedAt: integer('channelsFetchedAt'), // Unix timestamp
    emojis: text('emojis', { mode: 'json' }), // Cached emojis
    emojisFetchedAt: integer('emojisFetchedAt'), // Unix timestamp
    passwordHash: text('passwordHash'),
    customName: text('customName'),
    customIcon: text('customIcon'),
    serverType: text('serverType').default('normal'),
});
export const reminders = sqliteTable('reminders', {
    id: text('id').primaryKey(), // UUID generated by crypto.randomUUID()
    serverId: text('serverId'),
    createdBy: text('createdBy'),
    channel: text('channel'),
    channelId: text('channelId'),
    message: text('message'),
    startTime: text('startTime'), // ISO8601 string
    recurrence: text('recurrence', { mode: 'json' }), // Recurrence rules
    status: text('status'), // 'active', 'paused', 'processing'
    notificationOffsets: text('notificationOffsets', { mode: 'json' }), // Array of numbers
    selectedEmojis: text('selectedEmojis', { mode: 'json' }), // Array of strings
    hideNextTime: integer('hideNextTime', { mode: 'boolean' }).default(false),
    nextNotificationTime: text('nextNotificationTime'), // ISO8601 string
    nextOffsetIndex: integer('nextOffsetIndex'),
    order: integer('order'),
});
export const auditLogs = sqliteTable('audit_logs', {
    id: integer('id').primaryKey({ autoIncrement: true }),
    user: text('user'),
    action: text('action'),
    reminderMessage: text('reminderMessage'),
    before: text('before', { mode: 'json' }),
    after: text('after', { mode: 'json' }),
    serverId: text('serverId'),
    timestamp: text('timestamp'), // ISO8601 string
});
export const missedNotifications = sqliteTable('missed_notifications', {
    id: integer('id').primaryKey({ autoIncrement: true }),
    serverId: text('serverId'),
    reminderMessage: text('reminderMessage'),
    missedAt: text('missedAt'), // ISO8601 string
    channelName: text('channelName'),
    acknowledged: integer('acknowledged', { mode: 'boolean' }).default(false),
});
